project:
  type: website
  output-dir : docs  
website:
  title: "수로뻥~!"
  page-navigation: true
  navbar:
    right:
      - icon : github
        href : https://github.com/gangcheol/
  sidebar:
    style: "docked"
    search: True
    contents: auto
    
format:
  html:
    theme : materia
    css : styles.css